# This reusable workflow depends on project to have following scripts
#   bin/audit
#   bin/lint
#   bin/test

name: Build app image and run checks
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      # See: https://github.com/docker-library/docs/blob/master/postgres/README.md#supported-tags-and-respective-dockerfile-links
      postgres_version:
        description: Postgres version for running tests (eg. 13.6)
        required: true
        type: string

      # See: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
      runner:
        description: Set the runner for the workflow (eg. ubuntu-20.04)
        required: false
        type: string
        default: ubuntu-latest

      aws_region:
        description: AWS region
        required: false
        type: string

      environment:
        description: GitHub environment
        required: false
        type: string

      timeout_minutes:
        description: Workflow timeout
        required: false
        type: number
        default: 10

      target:
        description: Set the target build stage for the image (eg. test or deploy)
        required: false
        type: string

      context:
        description: Docker context
        required: false
        type: string
        default: "."

      file:
        description: Path to Dockerfile
        required: false
        type: string

      build_args:
        description: Docker build arguments
        required: false
        type: string

      param_store:
        description: Parameter store (supported options are aws-ssm, repo-file)
        required: true
        type: string

      aws_ssm_param_path:
        description: The hierarchy for the parameters
        required: false
        type: string

      param_mount_src:
        description: Params source path
        required: false
        type: string

      param_mount_dst:
        description: Params destination path in the application image, relative to the repo root (eg. config/application.yml)
        required: false
        type: string

jobs:
  build_image:
    name: Build app image and run checks
    runs-on: ${{ inputs.runner }}
    environment: ${{ inputs.environment }}
    timeout-minutes: ${{ inputs.timeout_minutes }}

    services:
      postgres:
        image: postgres:${{ inputs.postgres_version }}
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        if: ${{ inputs.param_store == 'aws-ssm' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}

      - name: Load AWS SSM parameters
        if: ${{ inputs.param_store == 'aws-ssm' }}
        id: pull-aws-ssm-params
        uses: infinum/param-store-aws-ssm@main
        with:
          path: ${{ inputs.aws_ssm_param_path }}
          file: ${{ inputs.param_mount_src }}

      - name: Build app image
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          target: ${{ inputs.target }}
          push: false
          load: true
          tags: app
          build-args: ${{ inputs.build_args }}
          secret-files: |
            app_secrets=${{ inputs.param_mount_src }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Lint
        run: |
          docker run \
            --mount type=bind,src=$PWD/${{ inputs.param_mount_src }},dst=/app/${{ inputs.param_mount_dst }} \
            app \
            bin/lint

      - name: Audit
        run: docker run app bin/audit

      - name: Test
        run: |
          docker run \
            --env DATABASE_HOST=localhost \
            --env DATABASE_USERNAME=postgres \
            --env DATABASE_PASSWORD=postgres \
            --network=host \
            --mount type=bind,src=$PWD/${{ inputs.param_mount_src }},dst=/app/${{ inputs.param_mount_dst }} \
            app \
            bin/test
