# This reusable workflow depends on project to have following scripts
#   bin/audit
#   bin/lint
#   bin/test

name: Build app image and run checks
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      # See: https://github.com/docker-library/docs/blob/master/postgres/README.md#supported-tags-and-respective-dockerfile-links
      postgres_version:
        description: Postgres version for running tests (eg. 13.6)
        required: true
        type: string

      postgres_timeout_minutes:
        description: Postgres service timeout
        required: false
        type: integer
        default: 1

      # See: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
      runner:
        description: Set the runner for the workflow (eg. ubuntu-20.04)
        required: false
        type: string
        default: ubuntu-latest

      timeout_minutes:
        description: Workflow timeout
        required: false
        type: integer
        default: 10

      target:
        description: Set the target build stage for the image (eg. test or deploy)
        required: false
        type: string

      context:
        description: Docker context
        required: false
        type: string
        default: "."

      file:
        description: Path to Dockerfile
        required: false
        type: string

      build_args:
        description: Docker build arguments
        required: false
        type: string

      secret_mount_src:
        description: Secret source path, relative to the repo root (eg. infra/ci/docker/application.yml)
        required: false
        type: string

      secret_mount_dst:
        description: Secret destination path in the application image, relative to the repo root (eg. config/application.yml)
        required: false
        type: string

jobs:
  build_image:
    name: Build app image and run checks
    runs-on: ${{ inputs.runner }}
    timeout-minutes: ${{ inputs.timeout_minutes }}

    services:
      postgres:
        image: postgres:${{ inputs.postgres_version }}
        env:
          POSTGRES_PASSWORD: postgres

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build app image
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          target: ${{ inputs.target }}
          push: false
          load: true
          tags: app
          build-args: ${{ inputs.build_args }}
          secret-files: |
            app_secrets=${{ inputs.secret_mount_src }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Lint
        run: |
          docker run \
            --mount type=bind,src=$PWD/${{ inputs.secret_mount_src }},dst=/app/${{ inputs.secret_mount_dst }} \
            app \
            bin/lint

      - name: Audit
        run: docker run app bin/audit

      - name: Wait for Postgres to be ready
        timeout-minutes: ${{ inputs.pg_timeout_minutes }}
        run: until docker exec postgres pg_isready; do sleep 1; done

      - name: Test
        run: |
          docker run \
            --env DATABASE_HOST=postgres \
            --env DATABASE_USERNAME=postgres \
            --env DATABASE_PASSWORD=postgres \
            --network=host \
            --mount type=bind,src=$PWD/${{ inputs.secret_mount_src }},dst=/app/${{ inputs.secret_mount_dst }} \
            app \
            bin/test
