name: Release Rails CI/CD pipeline templates

on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version-file: package.json
      - run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify:
    name: Send Slack notification
    uses: infinum/devops-pipelines/.github/workflows/slack-notification.yml@v2.1.1
    needs: release
    if: ${{ always() }}
    with:
      outcome: ${{ needs.release.result }}
      channel: rails-apps-notifications
      color: ${{ needs.release.result }}
      title: "Rails CI/CD pipeline released"
    secrets: inherit
